### ISSUE TITLE
print(#(foo)) causes syntax error on dim foo() line

### ISSUE THREAD

**Issue by jurkstas** [at67/gigatron-rom#6]
Tested on version: gtEMU67 v1.0.6
```
_runtimePath_ "./runtime"
cls
dim foo(1) =0xFFF, 0xFFFF
print(#(foo))
```
Notice the extra ().

Result:
`Compiler::sizeOf() : Syntax error in 'dim foo(1) =0xFFF, 0xFFFF' on line 3`

This works fine:
```
_runtimePath_ "./runtime"
cls
dim foo(1) =0xFFF, 0xFFFF
print(#foo)
```
Result as expected (on emulator screen): `4`

**Comment by jurkstas** [comment]
The error:
https://github.com/at67/gigatron-rom/blob/712f9e2d718bf50430d936d7a482a6956fce029d/Contrib/at67/compiler.cpp#L2740

**Comment by at67** [comment]
Checking it out now, will report back when I have it sorted.

**Comment by at67** [comment]
This bug and many more syntax error handling bugs should be fixed now, error handling as a whole is still nowhere near perfect though.

**Comment by jurkstas** [comment]
Commit: df65221457e6599fb625b2b9305b63a1bcb5be3c

**Comment by at67** [comment]
I won't close this issue for now, when and if you feel happy that it is satisfied you can close it; that way you can reopen it at a later date if need be, (if I close it, you won't be able to re-open it).
