### ISSUE TITLE
Documentation notes

### ISSUE THREAD

**Issue by jurkstas** [at67/gigatron-rom#8]
I know that documentation is in the works. I am creating this issue to have a place for documentation notes. Essentially stuff that I find out by experimenting instead of RTFM.

- [ ] `_runtimePath_` (maybe other pragmas too, to be tested) must be in the main code module, not in `MODULE"foo.gbas"`. It does not need to be before MODULEs though.

**Comment by at67** [comment]
Great idea and good pickup, I completely forgot that pragmas only work in the main module, (yes ALL pragmas must reside in the main module).
